// <auto-generated />
using System;
using DGT.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DGT.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DGT.Models.Conductor", b =>
                {
                    b.Property<string>("Dni")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Puntos")
                        .HasColumnType("int");

                    b.HasKey("Dni");

                    b.ToTable("Conductores");
                });

            modelBuilder.Entity("DGT.Models.ConductorVehiculo", b =>
                {
                    b.Property<string>("Dni")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Matricula")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Dni", "Matricula");

                    b.HasIndex("Matricula");

                    b.ToTable("ConductorVehiculos");
                });

            modelBuilder.Entity("DGT.Models.Infraccion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DescuentoPuntos")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Infracciones");
                });

            modelBuilder.Entity("DGT.Models.Sancion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ConductorDni")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<string>("VehiculoMatricula")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ConductorDni");

                    b.HasIndex("VehiculoMatricula");

                    b.ToTable("Sanciones");
                });

            modelBuilder.Entity("DGT.Models.Vehiculo", b =>
                {
                    b.Property<string>("Matricula")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("InfraccionId")
                        .HasColumnType("int");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Matricula");

                    b.HasIndex("InfraccionId");

                    b.ToTable("Vehiculos");
                });

            modelBuilder.Entity("DGT.Models.ConductorVehiculo", b =>
                {
                    b.HasOne("DGT.Models.Conductor", "Conductor")
                        .WithMany("ConductorVehiculos")
                        .HasForeignKey("Dni")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DGT.Models.Vehiculo", "Vehiculo")
                        .WithMany("ConductorVehiculos")
                        .HasForeignKey("Matricula")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DGT.Models.Sancion", b =>
                {
                    b.HasOne("DGT.Models.Conductor", "Conductor")
                        .WithMany()
                        .HasForeignKey("ConductorDni");

                    b.HasOne("DGT.Models.Vehiculo", "Vehiculo")
                        .WithMany()
                        .HasForeignKey("VehiculoMatricula");
                });

            modelBuilder.Entity("DGT.Models.Vehiculo", b =>
                {
                    b.HasOne("DGT.Models.Infraccion", "Infraccion")
                        .WithMany()
                        .HasForeignKey("InfraccionId");
                });
#pragma warning restore 612, 618
        }
    }
}
